"""Generar migración inicial desde models.py

Revision ID: b3b733926356
Revises: 
Create Date: 2024-11-11 00:21:19.206666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3b733926356'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('configuracion_sistema',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clave', sa.String(length=100), nullable=False),
    sa.Column('valor', sa.Text(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('ultima_actualizacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clave')
    )
    op.create_table('estado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_usuario', sa.String(length=150), nullable=False),
    sa.Column('contrasena', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.Enum('ADMIN', 'USUARIO', 'PROFESOR', 'ALUMNO', name='roleenum'), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuario_nombre_usuario'), 'usuario', ['nombre_usuario'], unique=True)
    op.create_index(op.f('ix_usuario_rol'), 'usuario', ['rol'], unique=False)
    op.create_table('formula_petition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('petition_id', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('requiere_rele', sa.String(length=50), nullable=True),
    sa.Column('telefono_contacto', sa.String(length=20), nullable=False),
    sa.Column('foto_receta_path', sa.String(length=255), nullable=True),
    sa.Column('fecha_solicitud', sa.DateTime(), nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.Column('fecha_preparacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_entrega', sa.DateTime(), nullable=True),
    sa.Column('notas_laboratorio', sa.Text(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('preparado_por_id', sa.Integer(), nullable=True),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categoria.id'], ),
    sa.ForeignKeyConstraint(['preparado_por_id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('petition_id')
    )
    op.create_table('producto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('codigo', sa.String(length=50), nullable=True),
    sa.Column('estado_id', sa.Integer(), nullable=False),
    sa.Column('usuario_asignado', sa.Integer(), nullable=True),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.Column('fecha_asignacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_devolucion', sa.DateTime(), nullable=True),
    sa.Column('fecha_alta', sa.DateTime(), nullable=False),
    sa.Column('ultima_actualizacion', sa.DateTime(), nullable=True),
    sa.Column('rfid_tag', sa.String(length=100), nullable=True),
    sa.Column('ultimo_escaneo', sa.DateTime(), nullable=True),
    sa.Column('ubicacion_actual', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categoria.id'], name='fk_formula_categoria'),
    sa.ForeignKeyConstraint(['estado_id'], ['estado.id'], ),
    sa.ForeignKeyConstraint(['usuario_asignado'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo'),
    sa.UniqueConstraint('rfid_tag', name='uq_producto_rfid_tag')
    )
    op.create_table('auditoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('formula_id', sa.Integer(), nullable=True),
    sa.Column('accion', sa.String(length=150), nullable=False),
    sa.Column('fecha_hora', sa.DateTime(), nullable=False),
    sa.Column('detalle', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['formula_id'], ['formula_petition.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('escaneo_rfid',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('fecha_hora', sa.DateTime(), nullable=False),
    sa.Column('ubicacion', sa.String(length=100), nullable=True),
    sa.Column('lector_id', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['producto_id'], ['producto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('formula_producto',
    sa.Column('formula_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Float(), nullable=False),
    sa.Column('unidad', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['formula_id'], ['formula_petition.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['producto.id'], ),
    sa.PrimaryKeyConstraint('formula_id', 'producto_id')
    )
    op.create_table('movimiento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('formula_id', sa.Integer(), nullable=True),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('estado_anterior', sa.String(length=50), nullable=False),
    sa.Column('estado_nuevo', sa.String(length=50), nullable=False),
    sa.Column('fecha_hora', sa.DateTime(), nullable=False),
    sa.Column('detalle', sa.Text(), nullable=True),
    sa.Column('duracion_dias', sa.Integer(), nullable=True),
    sa.Column('razon', sa.Text(), nullable=True),
    sa.Column('fecha_hora_devolucion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['formula_id'], ['formula_petition.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['producto.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notificacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mensaje', sa.String(length=250), nullable=False),
    sa.Column('fecha_hora', sa.DateTime(), nullable=False),
    sa.Column('leida', sa.Boolean(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('prioridad', sa.Integer(), nullable=True),
    sa.Column('link', sa.String(length=255), nullable=True),
    sa.Column('formula_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['formula_id'], ['formula_petition.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('solicitud_prestamo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('fecha_solicitud', sa.DateTime(), nullable=False),
    sa.Column('duracion_dias', sa.Integer(), nullable=False),
    sa.Column('razon', sa.Text(), nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.Column('fecha_aprobacion', sa.DateTime(), nullable=True),
    sa.Column('aprobado_por', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['aprobado_por'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['producto.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('solicitud_prestamo')
    op.drop_table('notificacion')
    op.drop_table('movimiento')
    op.drop_table('formula_producto')
    op.drop_table('escaneo_rfid')
    op.drop_table('auditoria')
    op.drop_table('producto')
    op.drop_table('formula_petition')
    op.drop_index(op.f('ix_usuario_rol'), table_name='usuario')
    op.drop_index(op.f('ix_usuario_nombre_usuario'), table_name='usuario')
    op.drop_table('usuario')
    op.drop_table('estado')
    op.drop_table('configuracion_sistema')
    op.drop_table('categoria')
    # ### end Alembic commands ###
